/* Auto-generated by gen-colors.sh — do not edit manually */
static const char wal_bg[]      = "#020101";  /* color0 - background         */
static const char wal_fg[]      = "#a7a7a6";  /* color7 - foreground         */
static const char wal_border[]  = "#747474";  /* color8 - inactive border    */
static const char wal_bg_sel[]  = "#40403F";  /* color4 - selected bg/border */
static const char wal_fg_sel[]  = "#020101";  /* color0 - selected fg        */
